### ISSUE TITLE
Update NPM and Yarn builds in finos-plexus.github.io to resolve GitHub security notifications

### ISSUE THREAD

**Issue by udalmik** [finos-plexus/finos-plexus.github.io#20]
Update NPM and Yarn builds in plexus-interop and plexus.github.io to resolve the GitHub security notifications listed below:
https://github.com/finos-plexus/finos-plexus.github.io/network/alerts

Similar to finos-plexus/plexus-interop#123

**Comment by mcleo-d** [comment]
Transferred issue to finos-plexus.github.io to sit with the related project.

**Comment by mcleo-d** [comment]
@lspiro-Tick42 - Can we assign this to a developer to resolve with @maoo as a matter of priority?

Many thanks,

James.

**Comment by mcleo-d** [comment]
No longer relevant on this project or repository.
