### ISSUE TITLE
Remove "finos-plexus.github.io" from Plexus Interop metadata gitHubRepos array

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/finos-plexus.github.io#21]
### Description of Problem:
The repository "finos-plexus.github.io" is reflected in the Plexus Interop metadata getHubRepos array

### Potential Solutions:
The repository "finos-plexus.github.io" should be removed from the Plexus Interop metadata getHubRepos array

### Related Issues:
_[GitHub Issue 120](https://github.com/finos-plexus/plexus-interop/issues/120) : Confirm "finos-plexus.github.io" is appropriate repo name for Plexus Interop API Project_

**Comment by mcleo-d** [comment]
@maoo - For some reason I'm unable to assign this issue to you. Can you add yourself to the finos-plexus.github.io team? James.

**Comment by mcleo-d** [comment]
Transferred issue to finos-plexus.github.io to sit with the related project.

**Comment by mcleo-d** [comment]
Hi @maoo,

Can this issue be closed if https://github.com/finos/metadata/blob/dev/programs/plexus/plexus-interop/activity-metadata.json correctly represents the repos associated with the Plexus project?

Many thanks,

James.

**Comment by maoo** [comment]
Yes, all done, closing issue. TY!
